### PR TITLE
ProblemSet2

### PR DESCRIPTION
**Pull request by fonga153**
I can't check answers with Travis.  I do see my second build(ProblemSet2b). I had changed the homework since question#5 answer was originally ChrY but you really wanted Chr22.  How do i switch to the second build on Travis?  thanks.

### CODE REVIEW

**Comment by jayhesselberth** [comment]
You need to resync your fork:

$ git remote add upstream https://github.com/MOLB7621/problem-set-2.git
$ git fetch upstream
$ git merge upstream/master

The next commit should trigger a Travis build on this pull request.

**Comment by fonga153** [comment]
Sorry i am probably doing this wrong again. I have done as you requested.  My original answer did have spaces, but my second answer removed the spaces. My third attempt i changed it from any gene to only chr22.  i have now added ProblemSet2d as my answer with chr22 for Question#5.  On travis, I see it as 1 test but no failures or successes? thoughts? sorry...

**Comment by jayhesselberth** [comment]
the answer fields should have hyphens, not underscores:
```
# yes
answer-1: 123
# no
answer_1: 123
```

**Comment by fonga153** [comment]
Thank you for all your help!

**Comment by jayhesselberth** [comment]
strong work. :+1:

**Pull request closed without merging**
